package co.finema.etdassi.common.utils

enum class FragmentOrigin {
    REGISTER_DETAIL,
    REGISTER_DETAIL_SUCCESS,
    REGISTER_EWALLET,
    REGISTER_EWALLET_SUCCESS,
    REGISTER_VERIFY_EMAIL,
    START_REGISTER,
    BACKUP_STEP,
    START_SETPASSCODE,
    SET_PASSCODE,
    CONFIRM_PASSCODE,
    ENABLE_BIOMETRIC_LOGIN,
    REGISTER_FINISH,
    USER_PROFILE_MAIN_NEW_PINCODE,
    USER_PROFILE_MAIN_CONFIRM_PINCODE,
    USER_PROFILE_BACKUP,
    CHECK_PIN_CODE,
    CHECK_SYSTEM_PIN_CODE,
    VERIFY_VC,
    REGISTER_RECOVERY,
    RECOVERY_SUCCESS,
    RESET_DID
}

enum class DialogType {
    PRIVATE_KEY_INFO,
    DID_INFO
}