package co.finema.etdassi.common.enum

enum class RegisterState {
    REGISTER_MOBILE_SUCCESS,
    VERIFY_EMAIL_SUCCESS,
    RECOVERY_DID,
    RESET_DID_SUCCESS,
    REGISTER_DID_SUCCESS,
    REGISTER_SUCCESS,
    UPDATE_USER_SUCCESS,
    REGISTER_EWALLET_SUCCESS,
    BACKUP_WALLET_SUCCESS
}